### ISSUE TITLE
Recursive decoder : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by j-hotlink** [OvermindDL1/bucklescript-tea#109]
I have a recursive decoder (ocaml not reason), which BS is happy to compile:
    
```ocaml
let rec source_decoder () =
  Decoder.map4
    ( fun id name extra children ->
        { id = id
        ; name = name
        ; extra = extra
        ; children = children
        }
    )
    ( Decoder.field "id" Decoder.int )
    ( Decoder.field "name" Decoder.string )
    ( Decoder.field "extra" ( Decoder.nullable Decoder.string ) )
    ( Decoder.field "children" ( Decoder.list ( source_decoder () ) ) )
```

However the app fails to run and Chrome reports this error in the console (before the app startup code is reached - causing "starter.main" to be undefined):

```
Uncaught RangeError: Maximum call stack size exceeded
    at source_decoder (main.js:5728)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
    at source_decoder (main.js:5736)
(index):23 Uncaught TypeError: Cannot read property 'main' of undefined
    at (index):23
```

If I redefine the function without unit, like this:

```ocaml
let rec source_decoder =
  Decoder.map4
    ( fun id name extra children ->
        { id = id
        ; name = name
        ; extra = extra
        ; children = children
        }
    )
    ( Decoder.field "id" Decoder.int )
    ( Decoder.field "name" Decoder.string )
    ( Decoder.field "extra" ( Decoder.nullable Decoder.string ) )
    ( Decoder.field "children" ( Decoder.list ( source_decoder ) ) )
```

then I get the compilation error:

```
This kind of expression is not allowed as right-hand side of `let rec'
```

That error looks the same as this issue (https://github.com/reasonml-community/error-message-improvement/issues/25) which the OP says they fixed (solution unpublished), but I've no idea how to resolve this in ocaml.

Any advice much appreciated...

**Comment by OvermindDL1** [comment]
> That error looks the same as this issue (reasonml-community/error-message-improvement#25) which the OP says they fixed (solution unpublished), but I've no idea how to resolve this in ocaml.

ReasonML *is* OCaml, it's just a preprocessor on top of it, can use refmt to convert between them at will.  :-)

So the function is this:
```ocaml
let rec source_decoder () =
  Decoder.map4
    ( fun id name extra children ->
        { id = id
        ; name = name
        ; extra = extra
        ; children = children
        }
    )
    ( Decoder.field "id" Decoder.int )
    ( Decoder.field "name" Decoder.string )
    ( Decoder.field "extra" ( Decoder.nullable Decoder.string ) )
    ( Decoder.field "children" ( Decoder.list ( source_decoder () ) ) )
```
If we pare it down to the minimal bits, so we don't need the map to replicate this, only the last branch of it:
```ocaml
let rec source_decoder () =
  Decoder.field "children" ( Decoder.list ( source_decoder () ) )
```
And of course it's not even reaching the field or list calls since it immediately recurses into the `source_decoder ()` call:
```ocaml
let rec source_decoder () =
  source_decoder ()
```
Thus this is what gets executed, it just infinitely calls itself upon first call, you'll blow either the stack or the heap in most languages, depending on how they are implemented unless they are fully TCO (which the javascript VM is not) in which case those would lock up with an infinite loop.  :-)

So to fix this a thunk needs to be created to 'delay' the recursive call to until it is actually and really needed, the most traditionally known thunk is `lazy` and thus `Tea.Json.Decoder.lazy_` is the call that you want.  :-)

So the code will be something like (assuming I have the syntax correct, I'm typing it out here in Github):
```ocaml
let rec source_decoder () =
  Decoder.map4
    ( fun id name extra children ->
        { id = id
        ; name = name
        ; extra = extra
        ; children = children
        }
    )
    ( Decoder.field "id" Decoder.int )
    ( Decoder.field "name" Decoder.string )
    ( Decoder.field "extra" ( Decoder.nullable Decoder.string ) )
    ( Decoder.field "children" ( Decoder.list ( Decoder.lazy_ (fun () -> source_decoder ()) ) ) )
```
Which since `lazy_` takes both a 1-arg empty-tuple function and your `source_decoder` is also a 1-arg empty-tuple function then you can shorten it to this:
```ocaml
let rec source_decoder () =
  Decoder.map4
    ( fun id name extra children ->
        { id = id
        ; name = name
        ; extra = extra
        ; children = children
        }
    )
    ( Decoder.field "id" Decoder.int )
    ( Decoder.field "name" Decoder.string )
    ( Decoder.field "extra" ( Decoder.nullable Decoder.string ) )
    ( Decoder.field "children" ( Decoder.list ( Decoder.lazy_ source_decoder ) ) )
```
:-)


It's the same API as Elm though so following the Elm docs should work.  I really should make my own copy of the docs here sometime.  ^.^;

Please close this if it solves your issue so that I know it was successful, otherwise feel free to keep asking questions whether closed or not.  :-)

**Comment by j-hotlink** [comment]
Makes perfect sense - thanks for the fast, friendly and excellent advice!
