### ISSUE TITLE
Vdom bug

### ISSUE THREAD

**Issue by IwanKaramazow** [OvermindDL1/bucklescript-tea#13]
## Minimal case 
```Ocaml
type model = {
  selected: string option;
  languages: string list
}

type message = 
  | Select of string
  | Delete
  [@@bs.deriving {accessors}]

let render_selected = function
| Some selected -> 
  div [] 
    [ text ("you selected " ^ selected)
    ; div [onClick Delete] [text "delete selection"]]
| None -> div [] [text "Nothing selected"]

let lang l is_selected =
  let baseProps = [onClick (Select l); style "color" "blue"] in
  let props = if is_selected == true then (style "border" "1px solid black")::baseProps else baseProps
  in
  li props [text l]

let render_languages selected languages =
  let is_selected selected language =
  match selected with
      | Some l -> language == l
      | None -> false
  in 
  let rendered = List.map (fun l -> lang l (is_selected selected l)) languages in
  ul [] rendered

let update state = function 
| Select lang -> { state with selected = Some lang}
| Delete -> { state with selected = None }

let view state =
  div []
    [ render_selected state.selected 
    ; render_languages state.selected state.languages]

let main =
   let initialState = {
    selected = Some "Erlang"; 
    languages = ["Erlang"; "Ocaml"; "Clojure"]
   } in
   beginnerProgram { 
    model = initialState;
    update;
    view;
  }
```

## Background
![captura de pantalla 2017-02-24 a las 10 42 08](https://cloud.githubusercontent.com/assets/10634678/23298440/0611e178-fa7e-11e6-8026-c66b942e5fdb.png)

You have a list of `languages` where the first one is selected.
If a language is selected, it gets a border. Then, above the list,  a delete-link is displayed to deselect the selected language. 

## Expected
When deleting a language by clicking on the delete-link, the border should disappear.
All other styling (blue color) should remain, due to
```Ocaml
  let baseProps = [onClick (Select l); style "color" "blue"] in
  let props = if is_selected == true then (style "border" "1px solid black")::baseProps else baseProps
  in ...
```

## Actual
![captura de pantalla 2017-02-24 a las 10 49 32](https://cloud.githubusercontent.com/assets/10634678/23298705/f909e39e-fa7e-11e6-8fcc-56d272634936.png)
All style attributes on that list-item disappear, in favour of an empty style attribute.
I would expect the style to retain the "color: blue"

Unless I'm missing something pretty obvious, this looks like a bug in the vdom diffing.

**Comment by OvermindDL1** [comment]
Fascinating, let me look into this...

**Comment by OvermindDL1** [comment]
Ahh, it is hit by the fall-through condition because the order has changed, you are removing from the beginning instead of the end, which is perfectly valid and should not fail, just not a case a test for since all my code enables/disables inline.

For note, doing it the way you are by removing instead of disabling a property is inefficient as it will cause all the properties that occur 'after' it to be disabled and re-enabled again, which is definitely not what you want for performance.  The proper way to do this would be to change your `lang` function to be this instead:
```ocaml

let lang l is_selected =
  li
    [ onClick (Select l)
    ; style "color" "blue"
    ; if is_selected then style "border" "1px solid black" else noProp
    ]
    [ text l ]
```
I.E. instead of mutating the container, instead replace the specific property with `noProp` from `Vdom` (I just mirrored it into `Tea.Html` for ease of use too).  :-)

However, your case, inefficient though it may be, should still work, I'll fix it (and I have an idea to remove 'some' of the inefficiency cost too, though at the cost of slightly greater VDom overhead, so I'm unsure if I want to do it yet, I want to keep the base-line low).  :-)

**Comment by OvermindDL1** [comment]
Ah hah, and found out why that happens, it is because since the order changed from `[borderSet, onClick, colorBlue]` to `[onClick, colorBlue]` then what it is doing is comparing `borderSet` to `onClick` and seeing they do not equal, so it is clearing `borderSet` and setting `onClick`, then it goes to the next where it compares `onClick` to `colorBlue`, it is seeing they do not equal so it is clearing the `onClick` event handler (the old one thankfully, not the new one, since they are keyed into a cache) and setting `colorBlue`, then it is iterating and seeing a `colorBlue` on old but nothing on new, so it is clearing `colorBlue`, this is exactly how I designed it for speed reasons as I never intended for the length of the property or child lists to change, however it should still not break like this, so I am going to keep this fast path, however to fix this issue I can do one of two things...  I can throw an error of the lengths do not match, this will be the fastest as the code will not be run unless the lengths really do not match.  Or I can compare the lengths then re-create the entire node each time as it is effectively a different node, this might incur an overhead in the fast-path though... unless I catch the error from the handling then do a full-recreate (simple return value test), that would actually work and the speed hit would only happen in this specific bug case, hmm...  I should probably log a set of messages to the console on 'odd' conditions like this too...

**Comment by OvermindDL1** [comment]
And done, also logging a message on property list length change that says why and how to fix it.  Will commit shortly and release a new npm update.  Your example now works, but it logs a message that says how to fix the inefficiency.  :-)

**Comment by OvermindDL1** [comment]
And published.  :-)

Thanks for the bug reports @IwanKaramazow and keep them coming!  :-D

Plus keep poking me to add documentation (I need time ^.^), proper documentation would fix most of these, but still these cases need to be fixed regardless, so definitely keep them coming.  ^.^

**Comment by IwanKaramazow** [comment]
Muchas gracias for the quick bugfix & elaborate response.
I still have a lot to learn :D

**Comment by OvermindDL1** [comment]
> Muchas gracias for the quick bugfix & elaborate response.
> I still have a lot to learn :D

I still have a lot of docs to write.  ^.^
I built this to be very efficient for the ways I write (and working around some Elm's VDom inefficiencies that bugged me, a lot), I just really need to document what those are.  ^.^
