### ISSUE TITLE
model used in an `onChange` handler doesn't update after each render

### ISSUE THREAD

**Issue by tcoopman** [OvermindDL1/bucklescript-tea#36]
I might be doing something wrong here with ocaml, but I can't seem to find a solution. If I use the model in an `onChange` handler, the model is never updated (the initial model is always used).

The bug in code:

```ocaml
open Tea.App
open Tea.Html

type msg =
  | Increment
  | Set of int
  [@@bs.deriving {accessors}]

let init () = 4

let update model = function 
  | Increment -> model + 1
  | Set i -> i

let view_button title msg =
  button
    [ onClick msg
    ]
    [ text title
    ]

let view model =
  let bug foo =
    print_endline (string_of_int model);
    Set (int_of_string foo)
  in
  div
    []
    [ span
        [ style "text-weight" "bold" ]
        [ text (string_of_int model) ]
    ; br []
    ; view_button "Increment" Increment
    ; input' [onChange bug] []
    ]

let main =
  beginnerProgram { 
    model = init (); 
    update;
    view;
  }
```

Now every time you type something in the input field and press enter, the model is set to the correct value, but if you look at the console output it always prints **4**.
So the model in the `bug` function is never updated?

Am I doing something wrong or is this a bug.
Something that points in the direction of a bug is that if you change the `onClick` handler to `(bug "10")` the model has the correct value.
So this only is a problem in the `onChange` handler?

**Comment by tcoopman** [comment]
`onInput` shows the same problem, so it looks like it's a problem with `onCB` of vdom?

**Comment by jackalcooper** [comment]
Hi, @tcoopman . I got this before. Have you tried to key it? Like this:
```
onInput ~key:(pages |> string_of_int) (fun x ->......
```

**Comment by tcoopman** [comment]
@jackalcooper That does seem to change the outcome. With a key, it updates.
So is this still a bug? Is this expected behaviour or not?

**Comment by jackalcooper** [comment]
@tcoopman it is expected.

> Key it if you expect it to shift up/down on occasion.  Basically if a key matches then it does a detailed check, if the key does not match then it skips the entire detailed check and checks its neighbors instead.
Unique means that if the unique key changes then it just wipes it out entirely and creates a new node
This is mostly useful with things like textbox's or custom elements

**Comment by OvermindDL1** [comment]
> So is this still a bug? Is this expected behaviour or not?

It is part of how most VDom's work.  Specifically you are 'closing' around (in the closure sense) the model with your `bug` function, then that function is stored into the DOM's event handler.  As you cannot compare functions or closures for equality (just how javascript, and indeed most languages work), the VDom cannot test to see if it is changed or not, so it assumes that it does not change as long as nothing else about it changes.  If it does change and you want to update it then you have to tell it 'something' that it can use as a comparison to know 'when' a change has occurred.  Thus this is precisely what `key` is for, `key` let's you override the default checking (which is no comparison for function types because javascript) with something you control that is comparable, so if the key on the event callback changes, then it updates the callback.  :-)

So yeah, not a bug, it is how almost every VDom library works, just needs better documentation.

I've always wanted to *force* the key to be there on event handlers, but that would break compatibility with the Elm API, however it would fix this issue then (Elm has the same issue).  Thoughts?  Is it worth breaking compat in this one way to prevent this bug from ever occurring again?

**Comment by jackalcooper** [comment]
You mean handlers return a tuple of (vdom, key, unique)? I think a required
named arguments make more sense.

**Comment by OvermindDL1** [comment]
> You mean handlers return a tuple of (vdom, key, unique)? I think a required named arguments make more sense.

It really does in my opinion.

But I was saying that any 'event handler' like `onChange` takes a mandatory `key` argument instead of it being optional, that would break the Elm API but it would make this bug impossible then unless the user specifically tried for it.

**Comment by tcoopman** [comment]
Personally I would prefer to make this mandatory and also document why it's mandatory (basically the responses in this bug report).
For something like this, I wouldn't care about exact compatibility with the Elm API, because to me, this looks like the least surprising thing.

On the other hand, it would nice if there were some kind of "general" TEA documentation/specification that languages could adopt (like this and I guess [Fable-arch](http://fable.io/fable-arch/#/) is something similar), but I don't think that this is a realistic goal at this point. Furthermore I'm not sure if it would add that much value except for unified documentation. How cool would it be if you could have the elm-guide and choose your language before you start.

Anyway, that last part was off topic, but it's something that I think about sometimes.

**Comment by OvermindDL1** [comment]
> For something like this, I wouldn't care about exact compatibility with the Elm API, because to me, this looks like the least surprising thing.

Eh still Elm has the same thing though if a function is passed straight.  I do intend to make an 'extended' API that has a lot of these little elm-warts fixed though in time.

> On the other hand, it would nice if there were some kind of "general" TEA documentation/specification that languages could adopt (like this and I guess Fable-arch is something similar), but I don't think that this is a realistic goal at this point. Furthermore I'm not sure if it would add that much value except for unified documentation. How cool would it be if you could have the elm-guide and choose your language before you start.

Heh, that is quite a cool idea though, it really should be done!  :-)

**Comment by tcoopman** [comment]
I'm going to close this issue as it's clear for me. I do think we should check if we can start with some documentation for things like this.
