### ISSUE TITLE
Bug could be related to virtual DOM

### ISSUE THREAD

**Issue by jackalcooper** [OvermindDL1/bucklescript-tea#6]
This is the code to reproduce it (Bootstrap's css required).
I recorded a video to explain it because it's kind of hard for me to write it down without animation.
[video](https://youtu.be/zgHWgIKMFQw)

paginate.ml:

```OCaml

open Tea
open App
open Html

let rec range a b =
  if a > b then []
  else a :: range (a + 1) b

type model =
  { page : int
    ; pages : int
  }


type msg =
  | PriviousPage
  | NextPage
  | SelectPage of int
  | SetPages of int



let init () = { page=1; pages=10 }, Cmd.none


let update model = function
  | PriviousPage -> if model.page - 1 > 0 then
        let newModel = {model with page = model.page - 1} in
            newModel, Cmd.none
      else
        model, Cmd.none
  | NextPage -> let pageNew = model.page + 1 in
      if pageNew < model.pages + 1  then
        let newModel = {model with page = pageNew} in
            newModel, Cmd.none
      else
        model, Cmd.none
  | SelectPage pageNumber -> 
        (if pageNumber == model.page then
      let () = print_endline "Stay in the same page" in
        model, Cmd.none
      else
        let newModel = {model with page = pageNumber} in
          newModel, Cmd.none)
  | SetPages newPages ->
        {model with pages = newPages; page = 1}, Cmd.none

let subscriptions _model =
  Sub.none


let view model =
    let pages = model.pages in
  div [ ]
          [ input' [ type' "text"; class' "form-control";  model.pages |> string_of_int |> value; onInput (fun x -> 
          let newPages = try int_of_string x  with _ -> 10 in
          SetPages newPages) ] []
              ;ul [class' "pagination"]
            ( 
              let () =  Js.log model.page in
              let largerThanLeft = model.page - 1 >= 1 in
              let smallerThanRight = model.page + 1 <= pages in   
              List.concat [
                [ li [classList ["disabled", largerThanLeft != true]]
                  [ a [ href "javascript:void(0)"; onClick PriviousPage ]
                    [ text ([%raw "\"Previous\"" ] : string) ]
                  ]
                ]
                ; (
                    List.map (fun (index) -> 
                      li [classList ["active", index == model.page]]
                        [ a [ href "javascript:void(0)"; onClick (SelectPage index) ]
                          [ text (string_of_int index) ]
                        ]
                  ) 
                  (range 1 pages)
                )
                ; [
                   li [classList ["disabled", smallerThanRight != true]]
                  [ a [ href "javascript:void(0)"; onClick NextPage ]
                    [ text ([%raw "\"Next\"" ] : string) ]
                  ]
                ]
              ]
            )
          ]


let main =
  standardProgram {
    init;
    update;
    view;
    subscriptions;
  }

```

**Comment by OvermindDL1** [comment]
This is exactly the same thing as the previous issue.  :-)

Since your Next button DOM is in the same format as the links themselves then it gets mutated to the new format, which since the onClick is not keyed (you really need to start adding ~key:"blah" or so to your event handlers that can mutate) then it is not mutated on the DOM.  This issue, since it is a msg and not a callback since it is a simple `onClick` event would be solved by implicitly converting a key internally, but that would still not work on events that take and require actual functions.  I'm thinking I should probably make the optional `key` argument non-optional, that would solve it for sure in all cases...

Since this is a duplicate though, closing it, but still keeping the first one open to remind me to do 'something' about this as it is obviously an issue.  :-)

Thanks for the reports!  Keep them coming!  ^.^

**Comment by martindemello** [comment]
have you taken a look at lexifi's [ocaml-vdom](https://github.com/LexiFi/ocaml-vdom)? they mention adding bucklescript as a target someday, and they have presumably already shaken out the corner cases with keyed nodes. i've been trying it out for a small project and it's been a pretty good experience so far.

**Comment by jackalcooper** [comment]
@OvermindDL1 Now I'm feeling so guilty for creating to many issues for you! 😂😼

**Comment by OvermindDL1** [comment]
> have you taken a look at lexifi's ocaml-vdom? they mention adding bucklescript as a target someday, and they have presumably already shaken out the corner cases with keyed nodes. i've been trying it out for a small project and it's been a pretty good experience so far.

@martindemello I had and they have not (their project is also a lot newer than my VDom as well, I'm actually using mine in production), and it also does the same optional key argument style as well as you can see at https://github.com/LexiFi/ocaml-vdom/blob/master/lib/vdom.ml#L130 however with non-parameter events they take a message directly as at https://github.com/LexiFi/ocaml-vdom/blob/master/lib/vdom.ml#L48 and customizing it at https://github.com/LexiFi/ocaml-vdom/blob/master/lib/vdom_blit.ml#L515 and as at https://github.com/LexiFi/ocaml-vdom/blob/master/lib/vdom_blit.ml#L512 you see that they also take a function argument for events that pass in parameters, which you will have the same issue with those if you do not use the `key` value as well.

It is also the same way in other VDom implementations including https://github.com/Matt-Esch/virtual-dom (react and others are based on).  You have to use key's to be able to mutate callback-based event handlers, it is just the nature of javascript not being able to compare functions, so this will *always* appear somewhere.  What I am going to do is just *force* the user to always use a key when it is necessary instead of relying on the user being smart enough in the domain knowledge and using it correctly otherwise (which as has been seen in Elm, most people are not smart enough to know when or when not to use such things as they do not know the DOM or javascript well enough, I want to remove that avenue of breaking things via a bit of a redesign).  ^.^

> @OvermindDL1 Now I'm feeling so guilty for creating too many issues for you! 😂😼

@jackalcooper Nah, keep them coming!  ^.^
