### ISSUE TITLE
Alternative view html function syntax

### ISSUE THREAD

**Issue by eriklott** [OvermindDL1/bucklescript-tea#75]
I get the feeling that the view function is going to be a nightmare of parentheses for folks using the ReasonML syntax:

`
div([], [div([], [div([], [div([], [div([], [])])])])]);
`

I'm curious how much effort it would be to add support for JSX (if that is even possible). I might be willing to take a stab at it if you think it's worth while.

BTW: fantastic tea conversion into Bucklescript!

**Comment by OvermindDL1** [comment]
> I get the feeling that the view function is going to be a nightmare of parentheses for folks using the ReasonML syntax:

Lol, wow ReasonML is just getting worse isn't it...  ^.^;

> I'm curious how much effort it would be to add support for JSX (if that is even possible). 

It actually is quite possible, however it will execute slower than the current API (not by much or really even enough to worry about, but it is not free regardless).  It is on my todo list eventually though (probably with the planned refactor).  :-)

> I might be willing to take a stab at it if you think it's worth while.

It would just primarily be a set of bounce functions so it would be pretty easy to write.  If it can be contained to just a couple of functions then go ahead and PR it into the Tea_Html module, otherwise make a new module like Tea_JSX or so and PR that?  Otherwise I'll get around to it sometime (way busy time at work currently).  :-)

**Comment by OvermindDL1** [comment]
ReasonML doesn't even do type checking, it is a just a syntax transformer is all it is.  It's whole purpose is to help javascript programmers slowly transform to a better language (plus hey, more facebook lock-in doesn't hurt!), so if you already know OCaml, then just skip the intermediary step.  :-)

**Comment by eriklott** [comment]
Yeah, you're right. OCaml it is :) Thanks.
